Alina ulyanova/task 5
AlinaShmain/musical-service pull request #11
Opened 2021-06-07 10:48 UTC by AlinaShmain

2021-06-08 17:19 UTC, cyclist-nn requested changes

2021-06-08 17:19 UTC, cyclist-nn commented on frontend/package.json
> +    "@angular/cdk": "~11.2.13",
версии ангуляра давай брать без ~ и ^, причины на то есть и я расскажу потом когда время будет

2021-06-08 17:19 UTC, cyclist-nn commented on frontend/package.json
> +    "@ngrx/store-devtools": "^11.1.1",
тоже не надо ^, если надо обновить то версию измени

2021-06-08 17:19 UTC, cyclist-nn commented on frontend/src/custom-theme.scss
> +// For more information: https://material.angular.io/guide/theming
мы вроде обсуждали убрать этот файл, он все равно не работает так как scss не настроен в проекте

2021-06-08 17:19 UTC, cyclist-nn commented on frontend/src/ms-app/auth-modal/sign-in/sign-in.component.ts
> +      // this.cdr.markForCheck();
а если раскоментить то ломается чтоль?

2021-06-08 17:19 UTC, cyclist-nn commented on frontend/src/ms-app/material/material.module.ts
> +    MatDialogModule,
это не нормально то что экспортятся чужие модули

2021-06-08 17:19 UTC, cyclist-nn commented
посмотрел вчера и забыл запостить, пардон

2021-06-08 18:39 UTC, AlinaShmain commented on frontend/src/ms-app/auth-modal/sign-in/sign-in.component.ts
> +      // this.cdr.markForCheck();
Нет, просто пока это не нужно, я authenticated не использую пока нигде, разделение страниц для авторизованных и неавторизованных еще не делала

2021-06-08 18:41 UTC, AlinaShmain commented on frontend/src/ms-app/material/material.module.ts
> +    MatDialogModule,
то есть материал модули не выносить лучше в отдельный модуль?

2021-06-09 11:16 UTC, cyclist-nn commented on frontend/src/ms-app/material/material.module.ts
> +    MatDialogModule,
нет. Экспортируем мы только то что создали сами. Модули матириала пусть сам матириал и экспортирует и он это 100% делает. А вот импортировать надо.

2021-06-09 11:20 UTC, AlinaShmain commented on frontend/src/ms-app/material/material.module.ts
> +    MatDialogModule,
я закоммитила исправления

2021-06-09 13:20 UTC, merged