Alina ulyanova/favourites
AlinaShmain/musical-service pull request #15
Opened 2021-06-29 09:48 UTC by AlinaShmain

2021-07-01 11:28 UTC, cyclist-nn requested changes

2021-07-01 11:28 UTC, cyclist-nn commented on frontend/src/ms-app/auth-modal/sign-in/sign-in.component.ts
> +  constructor(private _fb: FormBuilder, private cdr: ChangeDetectorRef, private store: Store<AppState>, private router: Router,
надо уж или все приватные начинать с _ или не начинать, второе легче

2021-07-01 11:28 UTC, cyclist-nn commented on frontend/src/ms-app/modalEntry/modal-entry.ts
> +    constructor(public dialog: MatDialog, private router: Router, private route: ActivatedRoute, private store: Store<AppState>, private _modalService: ModalService) {
и тут

2021-07-01 11:28 UTC, cyclist-nn commented on frontend/src/ms-app/modalEntry/modal-entry.ts
> +        // const routes = this.router.url.split("/");
вообще везде много логов и закоменченого кода  - надо почистить весь проект

2021-07-01 11:28 UTC, cyclist-nn commented on frontend/src/ms-app/services/modal/modal.service.ts
> +            // takeUntil(this.destroy$),
в сервисах можно не отписываться

2021-07-01 11:28 UTC, cyclist-nn commented on frontend/src/ms-app/services/users/users.service.ts
> +    return this.http.post<Token>("http://localhost:3000/register", JSON.stringify(userData), httpOptions)
путь до бекенда лучше вынести в какое то одно место

2021-07-04 19:23 UTC, AlinaShmain commented
Можете замерджить этот пул реквест пожалуйста, описанные замечания я исправила в следующем реквесте, либо можете только следующий пул реквест замерджить, там есть все изменения, что и здесь плюс новые

2021-07-05 11:30 UTC, closed without merging